### ISSUE TITLE
_

### ISSUE THREAD

**Issue by aapclark** [Nicholas-Gebhart-Lambda-School/pt15-schedule#1]
![](https://i.kym-cdn.com/photos/images/original/000/909/741/14f.jpg)

**Comment by gebhartn** [comment]
Issue has been reviewed and resolved, see the [above commit](https://github.com/Nicholas-Gebhart-Lambda-School/pt15-schedule/commit/a895fc01ea5657350348b36ce5ca0e3e809b8e98) for fixes.
